apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: movie-app
  template:
    metadata:
      labels:
        app: movie-app
    spec:
      containers:
        - name: movie-app
          image: srujanpanthula/mutibranch-flask-app:build-2
          ports:
            - containerPort: 5000
