apiVersion: apps/v1
kind: deployment
metadata:
  name: movie-app
  namespace: default
spec:
  replicas: 5
  selctor:
    matchLabels:
      app: movie-app
  template:
    metadata:
      labels:
        app:movie-app
    spec:
      containers:
        - name: movie-app
          image: srujanpanthula/mutibranch-flask-app:build-6
          ports:
            - containerPort: 5000
